# Generated by Django 3.1.4 on 2020-12-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponse',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
