# Generated by Django 3.1.4 on 2020-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestresponse',
            old_name='response',
            new_name='detected_date_response',
        ),
        migrations.AddField(
            model_name='requestresponse',
            name='entity_detect_response',
            field=models.TextField(blank=True),
        ),
    ]
