# Generated by Django 3.1.4 on 2020-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201217_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='timezone',
            field=models.TextField(blank=True),
        ),
    ]
