# Generated by Django 3.1.4 on 2020-12-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requestresponse_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='spacyRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('entity_detect_response', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='timefhumanRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('timezone', models.TextField(blank=True)),
                ('detected_date_response', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestResponse',
        ),
    ]
